### ISSUE TITLE
🛑 FluffyxGaming is down

### ISSUE THREAD

**Issue by NightFuryVG** [Starlight-Community-Network/status.starlightgaming.network#33]
In [`6678e1b`](https://github.com/Starlight-Community-Network/status.starlightgaming.network/commit/6678e1bfde54736ebe4d6c90ae4f7c24e0124ea9
), FluffyxGaming (https://fluffyx.starlightgaming.network/) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by Thunderhawk-Gaming** [comment]
Fixed it was a stupid error to cause this to get flagged as down, sorry!
