### ISSUE TITLE
🛑 Blossom Rabbit lounge is down

### ISSUE THREAD

**Issue by NightFuryVG** [Starlight-Community-Network/status.starlightgaming.network#42]
In [`89e3d59`](https://github.com/Starlight-Community-Network/status.starlightgaming.network/commit/89e3d59698c8a29ff22d98b713fa8e8c7fbc30b0
), Blossom Rabbit lounge (https://Blossom.starlightgaming.network) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by Thunderhawk-Gaming** [comment]
DNS Related issue, sorry @NightFuryVG
